### ISSUE TITLE
Issue with webdriver-sync

### ISSUE THREAD

**Issue by kyo06** [jsdevel/webdriver-sync#103]
I have this issue when I create any webdriver on my script

OS : WIndows 7
JAVA_HOME : C:\Program Files\Java\jdk1.7.0_10
webdriver-sync version : 0.15.8

C:\Project\node_modules\webdriver-sync\node_modules
\java\lib\nodeJavaBridge.js:72
      result[methodName] = java.callStaticMethod.bind(java, name, methodName);
                         ^
TypeError: Cannot assign to read only property 'name' of function () {
    var args = [name];
    for (var i = 0; i < arguments.length; i++) {
      args.push(arguments...<omitted>... }
    at Java.java.import (C:\node_modules\we
bdriver-sync\node_modules\java\lib\nodeJavaBridge.js:72:26)
    at Object.By (C:\Project\node_modules\webdriver
-sync\src\imports.js:80:23)
    at Object.<anonymous> (C:\Project\node_modules\
webdriver-sync\src\classes\By.js:3:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projectt\node_modules\
webdriver-sync\src\interfaces\SearchContext.js:3:10)

Can you help me please to fix it,
Best Regards

**Comment by NickTulett** [comment]
What version of node?

I think I had this the other day building a Windows VM. I replaced node 0.12 with 0.10.36 and the problem went away.

**Comment by kyo06** [comment]
Thank you very much :) It works on 0.10.37 ^^

**Comment by jsdevel** [comment]
upgraded `node-java` to support `v0.12`.
