### ISSUE TITLE
TypeError: Cannot assign to read only property 'name' of function () (Mac and Node 0.12.0)

### ISSUE THREAD

**Issue by cgupta25** [jsdevel/webdriver-sync#104]
Running "mochacli:functional" (mochacli) task
/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/node_modules/java/lib/nodeJavaBridge.js:72
      result[methodName] = java.callStaticMethod.bind(java, name, methodName);
                         ^
TypeError: Cannot assign to read only property 'name' of function () {
    var args = [name];
    for (var i = 0; i < arguments.length; i++) {
      args.push(arguments...<omitted>... }
    at Java.java.import (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/node_modules/java/lib/nodeJavaBridge.js:72:26)
    at Object.By (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/imports.js:80:23)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/classes/By.js:3:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/interfaces/SearchContext.js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/interfaces/WebDriver.js:6:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/classes/WebDriverWait.js:9:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.WebDriverWait (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/node_modules/webdriver-sync/src/webdriver-sync.js:118:12)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/lib/webdriver_helper/utility.js:2:46)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/11main-testing/index.js:4:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/test/selenium_tests/functional/firstTest.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/test/workspace/11main/11main-internal/node_modules/grunt-mocha-cli/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/test/workspace/11main/11main-internal/node_modules/grunt-mocha-cli/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/Users/test/workspace/11main/11main-internal/node_modules/grunt-mocha-cli/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/Users/test/workspace/11main/11main-internal/node_modules/grunt-mocha-cli/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by NickTulett** [comment]
Can you use node 0.10.x instead?

**Comment by jsdevel** [comment]
Updated `node-java` to support `v0.12`.

**Comment by jsdevel** [comment]
[This](https://github.com/joeferner/node-java/pull/214) PR has the fix.
