### ISSUE TITLE
Having trouble with RemoteWebDriver

### ISSUE THREAD

**Issue by dirwin517** [jsdevel/webdriver-sync#110]
I want to run a Chrome Browser on a Remote SeleniumGrid
   
      var seleniumGridURL = 'http://localhostL4444/wd/hub';
      var wd = require('webdriver-sync');
      var ChromeDriver = wd.ChromeDriver;
      var RemoteWebDriver = wd.RemoteWebDriver;
      var desiredStuff = new wd.DesiredCapabilities.chrome();
      var driver = RemoteWebDriver(seleniumGridURL, desiredStuff);

But I get this error, after it spawns a chrome browser successfully on my selenium instance

/webdriver-sync/src/utils.js:6
  obj[prop] = val;
            ^
TypeError: Cannot set property '_instance' of undefined
  at addFinalProp (/webdriver-sync/src/utils.js:6:13)
  at RemoteWebDriver (/webdriver-sync/src/classes/RemoteWebDriver.js:132:3)

Also by any chance is there a way to give it a sessionId, looks like remoteWebDriver should have a setSessionId?
(we wanted to run protractor tests, but switch to webdriver-sync for any non angular intense operations)

**Comment by dirwin517** [comment]
nevermind, I forgot a new on the RemoteWebDriver

**Comment by dirwin517** [comment]
Also by any chance is there a way to give it a sessionId, looks like remoteWebDriver should have a setSessionId?
(we wanted to run protractor tests, but switch to webdriver-sync for any non angular intense operations)
