### ISSUE TITLE
Error: Could not create class org.openqa.selenium.chrome.ChromeDriver (OSX)

### ISSUE THREAD

**Issue by alisterscott** [jsdevel/webdriver-sync#116]
Not sure what I am doing wrong, but trying to create a new Chrome browser, I get this error:

```
$ node
> var wd = require('webdriver-sync');
undefined
> var ChromeDriver = wd.ChromeDriver;
Error: Could not create class org.openqa.selenium.chrome.ChromeDriver
java.lang.NoClassDefFoundError: org/openqa/selenium/chrome/ChromeDriver
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.chrome.ChromeDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (/Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/node_modules/java/lib/nodeJavaBridge.js:193:20)
    at Object.ChromeDriver (/Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/src/imports.js:83:23)
    at Object.<anonymous> (/Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/src/classes/ChromeDriver.js:3:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
I am on OSX 10.10.4.

I have installed:
* node v0.12.7
* java 1.8.0_45
* webdriver-sync 0.16.3
* node-java 0.54

When I installed webdriver-sync it didn't provide any errors:

```
$ npm install webdriver-sync
 
> java@0.5.3 install /Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/node_modules/java
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaScope.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/methodCallBaton.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/nodeJavaBridge.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/utils.o
  SOLINK_MODULE(target) Release/nodejavabridge_bindings.node

> selenium-binaries@0.3.6 install /Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/node_modules/selenium-binaries
> node ./lib/install.js


[selenium-binaries] Found Selenium at /Users/alisterscott/.selenium-binaries/selenium/2.45.0/selenium-server-standalone-2.45.0.jar

[selenium-binaries] Found chromedriver at /Users/alisterscott/.selenium-binaries/chromedriver/2.15/chromedriver

> java@0.5.3 postinstall /Users/alisterscott/Projects/webdriver-sync/node_modules/webdriver-sync/node_modules/java
> node postInstall.js

webdriver-sync@0.16.3 node_modules/webdriver-sync
├── async@0.2.10
├── selenium-binaries@0.3.6 (is-dir@1.0.0, async@0.9.2, mkdirp@0.5.1, which@1.1.1, unzip@0.1.11, download@0.1.19)
└── java@0.5.3 (async@0.9.0, find-java-home@0.1.2, nan@1.7.0, glob@5.0.5, lodash@3.7.0)
```

Any ideas?

**Comment by jsdevel** [comment]
@alisterscott were you able to resolve this?

**Comment by alisterscott** [comment]
I still face this issue on a particular mac. And I also found this issue comes up when running a simple script on Circle CI:
https://circleci.com/gh/alisterscott/webdriver-sync-demo/3
Any ideas?
