### ISSUE TITLE
Update to java 0.6.0

### ISSUE THREAD

**Issue by timonag** [jsdevel/webdriver-sync#125]
The module fails at installation because of issue with node 4.0.0 and java 0.5.5 as mentioned here https://github.com/joeferner/node-java/issues/250

Example from npm-debug.log
```
8186 verbose about to build node_modules/webdriver-sync/node_modules/java
8187 info build node_modules/webdriver-sync/node_modules/java
8188 info linkStuff java@0.5.5
8189 silly linkStuff java@0.5.5 has node_modules/webdriver-sync/node_modules as its parent node_modules
8190 verbose linkBins java@0.5.5
8191 verbose linkMans java@0.5.5
8192 verbose rebuildBundles java@0.5.5
8193 verbose rebuildBundles [ 'async', 'find-java-home', 'glob', 'lodash', 'nan' ]
8194 info install java@0.5.5
8195 verbose unsafe-perm in lifecycle true
8196 info postinstall selenium-binaries@0.3.7
8197 verbose unlock done using ~/.npm/_locks/selenium-binaries-04b8ffdc5bde66dc.lock for node_modules/webdriver-sync/node_modules/selenium-binaries
8198 info java@0.5.5 Failed to exec install script
8199 verbose unlock done using ~/.npm/_locks/java-682aa680e9cb7d8f.lock for node_modules/webdriver-sync/node_modules/java
8200 verbose about to build node_modules/webdriver-sync
8201 verbose unlock done using ~/.npm/_locks/webdriver-sync-4d8690ce2be63f87.lock for node_modules/webdriver-sync
8202 verbose stack Error: java@0.5.5 install: `node-gyp rebuild`
8202 verbose stack Exit status 1
8202 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
8202 verbose stack     at emitTwo (events.js:87:13)
8202 verbose stack     at EventEmitter.emit (events.js:172:7)
8202 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8202 verbose stack     at emitTwo (events.js:87:13)
8202 verbose stack     at ChildProcess.emit (events.js:172:7)
8202 verbose stack     at maybeClose (internal/child_process.js:817:16)
8202 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
8203 verbose pkgid java@0.5.5
8204 verbose cwd /opt/www/cms-ui-testing
8205 error Linux 3.19.0-25-generic
8206 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "webdriver-sync"
8207 error node v4.1.1
8208 error npm  v2.14.4
8209 error code ELIFECYCLE
8210 error java@0.5.5 install: `node-gyp rebuild`
8210 error Exit status 1
8211 error Failed at the java@0.5.5 install script 'node-gyp rebuild'.
8211 error This is most likely a problem with the java package,
8211 error not with npm itself.
8211 error Tell the author that this fails on your system:
8211 error     node-gyp rebuild
8211 error You can get their info via:
8211 error     npm owner ls java
8211 error There is likely additional logging output above.
8212 verbose exit [ 1, true ]
8213 verbose unbuild node_modules/webdriver-sync/node_modules/java
8214 info preuninstall java@0.5.5
8215 info uninstall java@0.5.5
8216 verbose unbuild rmStuff java@0.5.5 from node_modules
8217 verbose unbuild rmStuff in node_modules/webdriver-sync/node_modules
8218 info postuninstall java@0.5.5
8219 silly gentlyRm node_modules/webdriver-sync/node_modules/java is being purged from base 
8220 verbose gentlyRm don't care about contents; nuking node_modules/webdriver-sync/node_modules/java
8221 silly vacuum-fs purging node_modules/webdriver-sync/node_modules/java
8222 silly vacuum-fs quitting because other entries in node_modules/webdriver-sync/node_modules
8223 verbose unbuild node_modules/webdriver-sync
8224 info preuninstall webdriver-sync@0.16.5
8225 info uninstall webdriver-sync@0.16.5
8226 verbose unbuild rmStuff webdriver-sync@0.16.5 from node_modules
8227 info postuninstall webdriver-sync@0.16.5
8228 silly gentlyRm node_modules/webdriver-sync is being purged from base /opt/www/cms-ui-testing
8229 verbose gentlyRm don't care about contents; nuking node_modules/webdriver-sync
8230 silly vacuum-fs purging node_modules/webdriver-sync
8231 silly vacuum-fs quitting because other entries in node_modules
```

**Comment by jsdevel** [comment]
Thanks for submitting this @timonag !  See #125.

**Comment by timonag** [comment]
Thank you!
Tested both with node 0.12.7 and 4.1.1 - works like a charm.
