### ISSUE TITLE
Error creating ChromeDriver class

### ISSUE THREAD

**Issue by jugglinmike** [jsdevel/webdriver-sync#81]
[When this project updated its dependency on `selenium-binaries`](https://github.com/jsdevel/webdriver-sync/commit/1849498c04921a92355e917c96be67d034199b7f), it introduced an error in my test environment, triggered by accessing [the `ChromeDriver` property on this module's `exports` object](https://github.com/jsdevel/webdriver-sync/blob/cadc5f1e8a0b08f1acef23ba0af7ebdf94e65563/src/webdriver-sync.js#L30-L32).

Here's a partial stack trace:

```
Error: Could not create class org.openqa.selenium.chrome.ChromeDriver
java.lang.NoClassDefFoundError: org/openqa/selenium/chrome/ChromeDriver
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.chrome.ChromeDriver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

Here's the relevant section of the output generated by `npm ls`:

```
└─┬ webdriver-sync@0.15.0
  ├── async@0.2.10
  ├─┬ java@0.4.2
  │ ├─┬ find-java-home@0.1.1
  │ │ └── which@1.0.5
  │ ├─┬ glob@3.2.11
  │ │ ├── inherits@2.0.1
  │ │ └─┬ minimatch@0.3.0
  │ │   ├── lru-cache@2.5.0
  │ │   └── sigmund@1.0.0
  │ └── nan@1.2.0
  └─┬ selenium-binaries@0.2.0
    ├── async@0.9.0
    ├─┬ download@0.1.19
    │ ├─┬ decompress@0.2.5
    │ │ ├── adm-zip@0.4.4
    │ │ ├─┬ ext-name@1.0.1
    │ │ │ ├─┬ ext-list@0.2.0
    │ │ │ │ └─┬ got@0.2.0
    │ │ │ │   └── object-assign@0.3.1
    │ │ │ └── underscore.string@2.3.3
    │ │ ├── rimraf@2.2.8
    │ │ ├─┬ stream-combiner@0.0.4
    │ │ │ └── duplexer@0.1.1
    │ │ ├─┬ tar@0.1.20
    │ │ │ ├── block-stream@0.0.7
    │ │ │ ├─┬ fstream@0.1.31
    │ │ │ │ ├── graceful-fs@3.0.2
    │ │ │ │ └─┬ mkdirp@0.5.0
    │ │ │ │   └── minimist@0.0.8
    │ │ │ └── inherits@2.0.1
    │ │ └─┬ tempfile@0.1.3
    │ │   └── uuid@1.4.1
    │ ├── each-async@0.1.3
    │ ├── get-stdin@0.1.0
    │ ├── get-urls@0.1.2
    │ ├── mkdirp@0.3.5
    │ ├─┬ nopt@2.2.1
    │ │ └── abbrev@1.0.5
    │ ├─┬ request@2.42.0
    │ │ ├── aws-sign2@0.5.0
    │ │ ├─┬ bl@0.9.3
    │ │ │ └─┬ readable-stream@1.0.31
    │ │ │   ├── core-util-is@1.0.1
    │ │ │   ├── inherits@2.0.1
    │ │ │   ├── isarray@0.0.1
    │ │ │   └── string_decoder@0.10.31
    │ │ ├── caseless@0.6.0
    │ │ ├── forever-agent@0.5.2
    │ │ ├─┬ form-data@0.1.4
    │ │ │ ├─┬ combined-stream@0.0.5
    │ │ │ │ └── delayed-stream@0.0.5
    │ │ │ └── mime@1.2.11
    │ │ ├─┬ hawk@1.1.1
    │ │ │ ├── boom@0.4.2
    │ │ │ ├── cryptiles@0.2.2
    │ │ │ ├── hoek@0.9.1
    │ │ │ └── sntp@0.2.4
    │ │ ├─┬ http-signature@0.10.0
    │ │ │ ├── asn1@0.1.11
    │ │ │ ├── assert-plus@0.1.2
    │ │ │ └── ctype@0.5.2
    │ │ ├── json-stringify-safe@5.0.0
    │ │ ├── mime-types@1.0.2
    │ │ ├── node-uuid@1.4.1
    │ │ ├── oauth-sign@0.4.0
    │ │ ├── qs@1.2.2
    │ │ ├── stringstream@0.0.4
    │ │ ├─┬ tough-cookie@0.12.1
    │ │ │ └── punycode@1.3.1
    │ │ └── tunnel-agent@0.4.0
    │ └─┬ through2@0.4.2
    │   ├─┬ readable-stream@1.0.31
    │   │ ├── core-util-is@1.0.1
    │   │ ├── inherits@2.0.1
    │   │ ├── isarray@0.0.1
    │   │ └── string_decoder@0.10.31
    │   └─┬ xtend@2.1.2
    │     └── object-keys@0.4.0
    ├── is-dir@1.0.0
    ├─┬ mkdirp@0.5.0
    │ └── minimist@0.0.8
    ├─┬ unzip@0.1.11
    │ ├─┬ binary@0.3.0
    │ │ ├── buffers@0.1.1
    │ │ └─┬ chainsaw@0.1.0
    │ │   └── traverse@0.3.9
    │ ├─┬ fstream@0.1.31
    │ │ ├── graceful-fs@3.0.2
    │ │ ├── inherits@2.0.1
    │ │ └── rimraf@2.2.8
    │ ├─┬ match-stream@0.0.2
    │ │ └── buffers@0.1.1
    │ ├─┬ pullstream@0.4.1
    │ │ ├── over@0.0.5
    │ │ └── slice-stream@1.0.0
    │ ├─┬ readable-stream@1.0.31
    │ │ ├── core-util-is@1.0.1
    │ │ ├── inherits@2.0.1
    │ │ ├── isarray@0.0.1
    │ │ └── string_decoder@0.10.31
    │ └── setimmediate@1.0.2
    └── which@1.0.5
```

**Comment by jsdevel** [comment]
@jugglinmike I just bumped `selenium-binaries` to `0.3.0`.  Please re-open if the problem appears again.  Thanks!

**Comment by NickTulett** [comment]
This is a known problem in ChromeDriver - certainly in my case I am using Jenkins

https://sites.google.com/a/chromium.org/chromedriver/help/chrome-doesn-t-start
